bt: Fix NPE in BroadcastReceiver
java.lang.RuntimeException: Error receiving broadcast Intent {
act=android.bluetooth.device.action.CONNECTION_ACCESS_REPLY (has extras)
} in android.bluetooth.BluetoothDeviceProfileState$1@407e8ed0
	at
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:722)
	at android.os.Handler.handleCallback(Handler.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at com.android.server.ServerThread.run(SystemServer.java:630)
Caused by: java.lang.NullPointerException
	at
android.bluetooth.BluetoothDeviceProfileState$1.onReceive(BluetoothDeviceProfileState.java:119)
	at
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:709)
	... 4 more

Change-Id: I3590f41040383a2fb0f54f305ac2e7fe526c2070